site_name: Software Engineering Notes
repo_url: https://github.com/RafsanMazumder/notes

docs_dir: src
site_dir: public

theme:
  name: ivory

plugins:
  - search
  - literate-nav:
      nav_file: navigation.md