name: Deploy MkDocs

on:
  push:
    branches: [ main ]  # Or 'master' if that's your default branch name

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for .GitInfo and .Lastmod

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          mkdocs gh-deploy --force